### ISSUE TITLE
ZelNode Error: Failed to find daemon application

### ISSUE THREAD

**Issue by miaunik** [zelcash/zelcash#114]
Hello,

I get this error when I start my Zelnode on my VPS Error: Failed to find daemon application

When I delete zelnode=1 to my Zelcash.conf daemon start whithout problem.
I don't have any idea what the problem

Please can you help me?

**Comment by XK4MiLX** [comment]
to correct work u need put zelcash daemon and zelbench binary to /usr/local/bin if u want more info jone zel discord

**Comment by miaunik** [comment]
Please can you give me you #.... for discord?
