### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by dk808** [zelcash/zelcash#13]
Might be helpful to others that don't know.
![image](https://user-images.githubusercontent.com/41762330/50527751-22b6e480-0a9f-11e9-9433-c3320dbbbeed.png)

**Comment by Scribbles-MCAMK** [comment]
Thanks for the suggestion @dk808 
This should make things clearer: [https://github.com/zelcash/zelcash/commit/56596189b3ab94be6bb3174bda5b3b6b24a0a83a](url)
