### ISSUE TITLE
ZelCash v3.0.0 fails to run/build on CentOS 7.x

### ISSUE THREAD

**Issue by mawenpeng** [zelcash/zelcash#19]
Downloaded Linux binary release, run failed.

$ ./zelcashd
./zelcashd: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./zelcashd)
./zelcashd: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./zelcashd)
./zelcashd: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./zelcashd)
./zelcashd: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./zelcashd)

When building, run "./zcutil/build.sh -j$(nproc)", failed at the first time, run again, succeeded but run zelcashd failed.

$ ./src/zelcashd 
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted

In config.log, it shows errors like:
conftest.cpp:59:34: fatal error: libdb62/db_cxx.h: No such file or directory
       #include <libdb62/db_cxx.h>
                                  ^
Seems like requiring libdb6.x, but the OS has libdb5.x installed by default.
 
OS info:
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core

**Comment by Scribbles-MCAMK** [comment]
Hey: We do not officially support CentOS, and this is not supported with our build instructions.

But you can try these instructions: 

```sudo yum install \
autoconf libtool unzip git python \
wget curl  automake gcc gcc-c++ patch \
glibc-static libstdc++-static
```

Please execute the below commands in order. 

```sudo yum install centos-release-scl-rh
sudo yum install devtoolset-3-gcc devtoolset-3-gcc-c++
sudo update-alternatives --install /usr/bin/gcc-4.9 gcc-4.9 /opt/rh/devtoolset-3/root/usr/bin/gcc 10
sudo update-alternatives --install /usr/bin/g++-4.9 g++-4.9 /opt/rh/devtoolset-3/root/usr/bin/g++ 10
scl enable devtoolset-3 bash
```
Then get source and build: 
```git clone https://github.com/zelcash/zelcash.git
cd zelcash
./zcutil/fetch-params.sh
./zcutil/build.sh -j$(nproc)
```

Let us know how you get on.

**Comment by mawenpeng** [comment]
Hi Miles,
Still got similar errors after running the commands above.
ZelCash 2.0.0 is OK with CentOS 7.x. 
The packages version of CentOS is always lagging behind Ubuntu.

**Comment by Scribbles-MCAMK** [comment]
Hmm ok. Could you try the latest ZCash version as you mentioned V2.0.3 and see if you can build from source (out of curiosity)?

We will look into supporting a wider array of linux distributions in the future. For now Ubuntu 16.04 is recommended. 

Thanks, 
Miles

**Comment by mawenpeng** [comment]
Hi Miles,
I have ZCash v2.0.3 build. It runs OK.
Thanks for the replies.

**Comment by Scribbles-MCAMK** [comment]
Hi, 
Ok well that tells me with a little tweaking we can get it working, I will look into merging v2.0.3 Zcash and hopefully we can get ZelCash to compile on Cent OS 7.x 

Thanks for the heads up on both issues. I will close them for now. 
Miles

**Comment by mawenpeng** [comment]
@Scribbles-MCAMK Please be aware that you may need to run zcutil/build.sh 2 times when building ZCash v2.0.3. The 1st time may fail, then run the 2nd time immediately without clean up.
zcashd runs well if build passed.

For ZelCash v3.0.0, running zcutil/build.sh 2 times, the build will succeed, but zelcashd cannot run.

**Comment by mawenpeng** [comment]
@Scribbles-MCAMK 
Hi Miles,
Finally, the build passed with zelcashd v3.0.0 running well.
I ran zcutil/build.sh again without clean up. 

I suppose it's network issue. The dependencies downloading might be interrupted during build. 
Running build.sh again and again resumed the dependencies downloading and finally succeeded.

Thanks again for your help.
Jonathan
