### ISSUE TITLE
a core dumped, when zelcashd started

### ISSUE THREAD

**Issue by rettym** [zelcash/zelcash#26]
I am going through all the steps wriiten on zelcash github ZelNodeinstallv2 and as result:
мар 01 21:40:38 ubuntuRomanmazay zelcashd[2310]: zelcashd: chain.cpp:93: CBlockIndex* CBlockIndex::GetAncestor(int): Assertion `pindexWalk->pprev' failed.
мар 01 21:40:38 ubuntuRomanmazay systemd[1]: zelcash.service: Main process exited, code=dumped, status=6/ABRT
мар 01 21:40:38 ubuntuRomanmazay systemd[1]: zelcash.service: Failed with result 'core-dump'.

**Comment by milesmanley** [comment]
Sorry for the late response, seems to be a system specific issue, closed for now please feel free to raise another issue if you are still running into this problem.
