### ISSUE TITLE
zel 3.3.0 node memory usage is higher than before after July 18th

### ISSUE THREAD

**Issue by lcgogo** [zelcash/zelcash#70]
I run some zel 3.3.0 node and the memory usage jumps from about 740MB to 880MB after July 18th. I am not sure it will increase more in the future. I will monitor and report it here.

![屏幕快照 2019-07-19 上午10 29 21](https://user-images.githubusercontent.com/8175573/61505419-593f5700-aa11-11e9-9369-08580130eda2.png)

**Comment by milesmanley** [comment]
Interesting, we'd like to hear back if you have any further reports. @lcgogo

**Comment by milesmanley** [comment]
Have not heard back from @lcgogo - please feel free to open another issue if you have any new data.
