### ISSUE TITLE
Please write down the stopped block height in release note

### ISSUE THREAD

**Issue by lcgogo** [zelcash/zelcash#95]
There is no update about the stopped block height in 3.3.3 release note.
And my 3.3.0 node stopped at some block height when I check the debug log.
The log told me the 3.3.0 release are not supported.

I always read the release note to get the upgrade information and there is no metions that 3.3.0 will useless on which block.

**Comment by TheTrunk** [comment]
Sorry about that, we should have been more clear about deprecation policy in the release description. 
Every release has a planned deprecation blockheight and users are notified about it by looking into console output/daemon warnings 2 weeks prior deprecation to ensure the network is running the latest version.
